### ISSUE TITLE
Validator component not rendering

### ISSUE THREAD

**Issue by ehvetsi** [Q42/vue-dotnet-validator#8]
Hi, 

i'm testing the validator, but, doesn't work to me.
when i try like the tutorial creating the viewmodel, and the html like tutorial and using:

```
import dotnetValidator from './dotnet-validator/dist/index.js';
Vue.component('validator-group', dotnetValidator.validatorGroup);
Vue.component('validator', dotnetValidator.validator());
```

i receive the message:
     "Cannot find module "./dotnet-validator/dotnet-validator"

Then i try:
import dotnetValidator from '../node_modules/vue-dotnet-validator/dist/index.js';

then, my outer html is:

```
<form asp-controller="Account" asp-action="Register" method="post">
    <span asp-validation-for="LastName"></span> 
     <button type="submit">Register</button>
</form>
```

and I receive the message: 

    "Field is missing!"

then, I try:

import dotnetValidator from '../node_modules/vue-dotnet-validator/dist/index.js';

```
new Vue({
  el: '#app',
  components: {
    validator: dotnetValidator.validator(),
    validatorGroup: dotnetValidator.validatorGroup
  }
})
```

but my outer html is:

```
<form asp-controller="Account" asp-action="Register" method="post">
    <validator></validator> 
   <button type="submit">Register</button>
</form>
```

can anyone help me?

What i doing wrong?

Sorry for my english, i'm brazilian.

**Comment by tdekoning** [comment]
Hello!

Have you tried to replace `<validator></validator>` with something like this?
```
<validator value="@Model.LastName" inline-template>
           <span asp-validation-for="LastName" ref="message"></span>
           <input type="text" asp-for="LastName" ref="field" v-model="val" />
        </validator>
```
The `validator` component needs to have a `ref="field"` element inside of it in order to function. This element can be a `<input>` or a `<select>`.

Also, you want to wrap your `<form>` element inside of a `<validator-group inline-template>` component and add a `v-on:submit="validate"` attribute to your `<form>` tag.
If you follow the readme entirely, it should work.

**Comment by ehvetsi** [comment]
yes, 

`<validator></validator>`

is the rendered HTML

on my original form i do this like you:

`<validator-group inline-template>
    <form asp-controller="Account" asp-action="Register" method="post" v-on:submit="validate">
        <validator value="@Model.LastName" inline-template>
           <span asp-validation-for="LastName" ref="message"></span>
           <input type="text" asp-for="LastName" ref="field" v-model="val" />
        </validator>
        <button type="submit">Register</button>
    </form>
</validator-group>`

**Comment by tdekoning** [comment]
Can you try to adjust your JavaScript to this:
```
Vue.component('validator-group', dotnetValidator.validatorGroup);
Vue.component('validator', dotnetValidator.validator());

new Vue({
  el: '#app'
})
```

**Comment by tdekoning** [comment]
@ehvetsi Did you get the library to work?

**Comment by ehvetsi** [comment]
No,  sorry,

Then I stop to use.
