### ISSUE TITLE
Libarary Usage Without Webpack

### ISSUE THREAD

**Issue by AbeBaehaki** [Q42/vue-dotnet-validator#9]
Hi,

Is it possible to use this library without having a `webpack` setup?
Just like [VeeValidate](http://vee-validate.logaretm.com/#usage) for example. You can just include `vee-validate.js` in the page, then use the `VeeValidate` component.

```html
  <script src="path/to/vue.js"></script>
  <script src="path/to/vee-validate.js"></script>
  <script>
    Vue.use(VeeValidate); // good to go.
  </script>
```

Cheers!

**Comment by tdekoning** [comment]
Hello,
Currently, that is not possible.

However, it might be a good idea to have that option as well. You are free to open a pull request, otherwise it might take a little bit time before i can add the feature myself
